### ISSUE TITLE
request access to lab cloud 

### ISSUE THREAD

**Issue by liyun831229** [Merck/bgc-pipeline#1]
Hi, I am interested in deepBGC and would like to try the pipeline, but the link to request access to lab cloud won't work. Is there any way you can help?

Thanks,
Yun

**Comment by Microbiology** [comment]
Hi @liyun831229 ! This is the repository for the manuscript reference files and code. The actual DeepBGC program code for you to use can be found here:

https://github.com/Merck/deepbgc

Please let us know if you have issues with that one.
